# demo 전체 카운트
GET http://127.0.0.1:8080/demo/totalcount

###

# demo 리스트
GET http://127.0.0.1:8080/demo/list

###

# demo 조회
GET http://127.0.0.1:8080/demo/1

###

# demo 등록
POST http://127.0.0.1:8080/demo
Content-Type: application/json

{
  "name": "단순색",
  "age": 18
}

###

# demo 수정
PUT http://127.0.0.1:8080/demo/3
Content-Type: application/json

{
  "name": "단순색",
  "age": 19
}
###

# demo 삭제
DELETE http://127.0.0.1:8080/demo/3

###